version: '3'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./personas:/app/personas
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=persona-script
    restart: unless-stopped